[package]
name = "fb"
version = "0.1.0"
authors = ["Athanaze <sacha.liechti@arsent.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.19.0"
image = "0.23.11"